controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # Required critics configuration
      critics: ["GoalDist", "PathDist", "PathAlign", "ObstacleDist", "PreferForward"]
      
      # Critic parameters
      GoalDist:
        scale: 5.0
      PathDist:
        scale: 32.0
        max_vel_x: 0.5
        max_vel_y: 0.0
      PathAlign:
        scale: 32.0
        max_vel_x: 0.5
        max_vel_y: 0.0
        path_distance: 0.5
        lookahead_time: 1.5
      ObstacleDist:
        scale: 0.7
        summation_type: 1  # (0 = sum, 1 = product)
        collision_cost: 100.0
        scale_radius: 5.0
      PreferForward:
        scale: 25.0
        penalty: 0.5
        max_vel_x: 0.5

      # Original DWB parameters
      desired_linear_vel: 0.5
      max_linear_vel: 0.8
      min_linear_vel: 0.1
      linear_acc_lim: 2.5
      linear_decel_lim: 2.5
      angular_acc_lim: 3.2
      max_angular_vel: 1.0
      min_angular_vel: 0.4
      sim_time: 1.7
      use_dwa: false
      debug_trajectory_details: false
