/**:
  ros__parameters:
    # Global parameters
    use_sim_time: False
    robot_base_frame: "base_link"
    global_frame: "map"
    robot_radius: 0.3
    transform_tolerance: 0.2

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: False
      prune_plan: True
      transform_tolerance: 0.1
      critics: ["GoalAlign", "PathAlign", "PathDist", "BaseObstacle", "GoalDist", "PreferForward"]

      # Critic configurations
      GoalAlign:
        enabled: True
        scale: 5.0
        max_vel_x: 0.5
        
      PathAlign:
        enabled: True
        scale: 32.0
        max_vel_x: 0.5
        path_distance: 0.5
        lookahead_time: 1.5
        
      PathDist:
        enabled: True
        scale: 32.0
        max_vel_x: 0.5
        
      BaseObstacle:
        enabled: True
        scale: 0.7
        summation_type: 1
        collision_cost: 100.0
        scale_radius: 5.0
        
      GoalDist:
        enabled: True
        scale: 5.0
        
      PreferForward:
        enabled: True
        scale: 25.0
        penalty: 0.5
        max_vel_x: 0.5

      # DWB core parameters
      sim_time: 1.7
      linear_acc_lim: 2.5
      linear_decel_lim: 2.5
      angular_acc_lim: 3.2
      max_linear_vel: 0.8
      min_linear_vel: 0.1
      max_angular_vel: 1.0
      min_angular_vel: 0.4
      use_dwa: False

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      map_topic: /map
      subscribe_to_updates: true

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    plugins: ["obstacle_layer", "inflation_layer"]

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
      planner_server:
        use_final_approach_orientation: false

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    waypoint_task_executor_plugin: "wait_at_waypoint"
    stop_on_failure: false
    wait_at_waypoint:
      enabled: True
      wait_duration: 1.0  # Seconds to wait at each waypoint

