amcl:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    plugin: "nav2_bt_navigator/BtNavigator"
    bt_xml_filename: ""
    default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 5.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 1.0
      yaw_goal_tolerance: 6.28
      stateful: true

    FollowPath:
      #plugin: "nav2_pure_pursuit_controller::PurePursuitController"
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 1.0
      max_linear_accel: 2.5
      max_linear_decel: 2.5
      lookahead_dist: 0.9 # Reduced from 0.9 to make path following tighter
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5 #0.9  # Reduced from 1.5 to prevent large shortcuts
      lookahead_time: 0.8 #0.9 # Reduced from 1.5 to be more responsive
      rotate_to_heading_angular_vel: 0.8
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.3
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: true
      max_allowed_time_to_collision: 2.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.5
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: false # Changed to true to ensure robot faces goal direction
      rotate_to_heading_min_angle: 0.6 # Slightly reduced from 0.8
      rotate_to_heading_yaw_tolerance: 0.2
      max_angular_accel: 3.2
      goal_dist_tol: 0.5
      allow_reversing: true
      trans_stopped_velocity: 0.01
      rotate_stopped_velocity: 0.01
      debug_trajectory_details: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 20
      height: 20
      origin_x: 10.0
      origin_y: 10.0
      resolution: 0.1
      footprint: "[[-0.6, -0.5], [-0.6, 0.5], [0.6, 0.5], [0.6, -0.5]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      track_unknown_space: false
      always_send_full_costmap: true

      # Explicitly disable static layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: false
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: front_left back_right
        front_left:
          topic: /gazebo_ros_laser_controller_front_left/out
          max_obstacle_height: 3.
          min_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: "PointCloud2"
        back_right:
          topic: /gazebo_ros_laser_controller_back_right/out
          max_obstacle_height: 3.
          min_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: "PointCloud2"

        lane_camera:
          topic: /lane_pointcloud
          data_type: PointCloud2
          expected_update_rate: 0.5
          marking: true
          clearing: false
          min_obstacle_height: -0.1
          max_obstacle_height: 0.1
          obstacle_range: 10.0
          raytrace_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.5
        inflation_radius: 0.4 # was 0.55

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      footprint: "[[-0.6, -0.5], [-0.6, 0.5], [0.6, 0.5], [0.6, -0.5]]"
      resolution: 0.05
      rolling_window: true
      width: 100
      height: 100
      origin_x: -25.
      origin_y: -25.
      plugins: ["obstacle_layer", "inflation_layer"]
      track_unknown_space: false
      always_send_full_costmap: true

      # Explicitly disable static layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: false
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: front_left back_right
        front_left:
          topic: /gazebo_ros_laser_controller_front_left/out
          max_obstacle_height: 3.
          min_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: "PointCloud2"
        back_right:
          topic: /gazebo_ros_laser_controller_back_right/out
          max_obstacle_height: 3.
          min_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: "PointCloud2"
        lane_camera:
          topic: /lane_pointcloud
          data_type: PointCloud2
          expected_update_rate: 0.5
          marking: true
          clearing: false
          min_obstacle_height: -0.1
          max_obstacle_height: 0.1
          obstacle_range: 10.0
          raytrace_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.0 #was 1.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: true
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 2.0
      use_astar: true
      allow_unknown: true

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    use_sim_time: true
    waypoint_task_executor_plugin: "wait_at_waypoint"

    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: false
      wait_duration: 1

behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
