planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    
    GridBased:
      interpolation_resolution: 0.1
      tolerance: 0.5
      allow_unknown: true
      use_final_approach_orientation: false
