ekf_filter_node_odom:
  ros__parameters:
    frequency: 50.0
    world_frame: odom  # Local frame
    odom_frame: odom
    base_link_frame: base_link
    
    # Wheel odometry
    odom0: /diff_drive/center/odom
    odom0_config: [true, true, false,  # X,Y position
                   false, false, true,  # Yaw
                   true, true, false,  # X,Y velocity
                   false, false, true]  # Yaw rate
    
    # IMU for angular velocity
    imu0: /demo/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true, true, false] 

    process_noise_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3]
 
    twist0: /demo/cmd_vel
    twist0_config: [false, false, false, # x, y, z pos
                    false, false, false, # roll, pitch, yaw pos
                    true,  true,  false, # x, y, z, vel
                    false, false, true, # roll, pitch, yaw vel
                    false, false, false] # ax, ay, az
    twist0_queue_size: 3
    twist0_rejection_threshold: 2.0

ekf_filter_node_map:
  ros__parameters:
    frequency: 50.0
    world_frame: map  # UTM frame
    odom_frame: odom
    base_link_frame: base_link
    
    # Input: NavSat-transformed GPS
    odom0: /odometry/navsat    # Input: NavSat-transformed GPS
    odom0_config: [true, true, false,  # X,Y position
                   false, false, false,
                   true, true, false,
                   false, false, false,
                   false, false, false]
    odom0_pose_rejection_threshold: 5.0  # Reject GPS poses with large deviations
    odom0_twist_rejection_threshold: 1.0  # Reject GPS velocities with large deviations

    odom1: /odometry/odom    # Input: NavSat-transformed GPS
    odom1_config: [true, true, false,  # X,Y position
                   false, false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom1_pose_rejection_threshold: 2.0  # Reject odometry poses with large deviations
    odom1_twist_rejection_threshold: 0.5  # Reject odometry velocities with large deviations

    #IMU for orientation
    # imu0: /demo/imu
    # imu0_config: [false, false, false,
    #               true, true, true,  # Roll, Pitch, Yaw
    #               true, true, false,
    #               false, false, false,
    #               false, false, false]
    process_noise_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3]
navsat_transform:
  ros__parameters:
    base_link_frame_output: base_link
    frequency: 50.0
    delay: 0.0
    magnetic_declination_radians: 0.0  # Set for your location
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: false  # Let EKF handle this
    publish_filtered_gps: true
    use_odometry_yaw: true  # Critical for orientation
    wait_for_datum: true
    datum: [38.1614789, -122.454630, 0.0]  # ETH Zurich example
